name: Demo Workflow
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get codebase
        uses: actions/checkout@v4
      - name: Install deps
        run: npm ci
      - name: Build the app
        run: npm run build
